"""Domain contracts for the multi-agent orchestration boundary."""

from .contracts import (
    AgentOutcome,
    AgentQuestion,
    BudgetCall,
    BudgetExhaustedError,
    BudgetSnapshot,
    Citation,
    ClarificationRequest,
    EvidenceItem,
    EvidenceLedger,
    EvidenceSourceType,
    RunBudget,
    SearchTrace,
    SelectionStrategy,
    SynthesisResult,
    WebSearchItem,
    WebSearchResult,
)
from .document_search import (
    DocumentSearchResult,
    DocumentSearchService,
    DocumentSearchStatus,
    DocumentSearchToolAdapter,
    SemanticDocumentSearchTool,
)
from .evidence_selection import (
    ConceptRoleSelector,
    ParagraphDirectSelector,
    SelectionRequest,
    SelectionResult,
    adapt_legacy_selector,
)
from .evidence import EvidenceLedgerBuilder, stable_evidence_id
from .ports import (
    AgentTool,
    AnswerSynthesizer,
    DocumentSearchTool,
    EvidenceSelector,
    WebSearchTool,
    require_agent_tool,
)
from .graph import AgentGraphDependencies, GraphDependencyError, build_agent_graph
from .orchestrator import AgentRunResult, MainAgent
from .state import AgentDecision, AgentGraphState, AgentStage, GraphStage, GraphState
from .policies import (
    BudgetDecision,
    BudgetPolicy,
    BudgetTimeoutError,
    call_with_budget,
    check_budget,
    enforce_budget,
    execute_with_budget,
    run_with_budget,
)
from .synthesis import EvidenceSynthesisService, SynthesisCitation, SynthesisOutput
from .web_search import (
    WebSearchAdapter,
    WebSearchProvider,
    WebSearchService,
    WebSearchToolAdapter,
)

__all__ = [
    "AgentOutcome",
    "AgentQuestion",
    "BudgetCall",
    "BudgetExhaustedError",
    "BudgetSnapshot",
    "Citation",
    "ClarificationRequest",
    "EvidenceItem",
    "EvidenceLedger",
    "EvidenceSourceType",
    "RunBudget",
    "SearchTrace",
    "SelectionStrategy",
    "SynthesisResult",
    "WebSearchItem",
    "WebSearchResult",
    "DocumentSearchResult",
    "DocumentSearchService",
    "DocumentSearchStatus",
    "DocumentSearchToolAdapter",
    "SemanticDocumentSearchTool",
    "SelectionRequest",
    "SelectionResult",
    "ParagraphDirectSelector",
    "ConceptRoleSelector",
    "adapt_legacy_selector",
    "EvidenceLedgerBuilder",
    "stable_evidence_id",
    "AgentTool",
    "AnswerSynthesizer",
    "DocumentSearchTool",
    "EvidenceSelector",
    "WebSearchTool",
    "require_agent_tool",
    "BudgetDecision",
    "BudgetPolicy",
    "BudgetTimeoutError",
    "call_with_budget",
    "check_budget",
    "enforce_budget",
    "execute_with_budget",
    "run_with_budget",
    "AgentDecision",
    "AgentGraphDependencies",
    "AgentGraphState",
    "AgentRunResult",
    "AgentStage",
    "GraphStage",
    "GraphDependencyError",
    "GraphState",
    "MainAgent",
    "build_agent_graph",
    "EvidenceSynthesisService",
    "SynthesisCitation",
    "SynthesisOutput",
    "WebSearchAdapter",
    "WebSearchProvider",
    "WebSearchService",
    "WebSearchToolAdapter",
]
