"""Domain contracts for the multi-agent orchestration boundary."""

from .contracts import (
    AgentOutcome,
    AgentQuestion,
    BudgetCall,
    BudgetExhaustedError,
    BudgetSnapshot,
    Citation,
    ClarificationRequest,
    EvidenceItem,
    EvidenceLedger,
    EvidenceSourceType,
    RunBudget,
    SearchTrace,
    SelectionStrategy,
)
from .document_search import (
    DocumentSearchResult,
    DocumentSearchService,
    DocumentSearchStatus,
    DocumentSearchToolAdapter,
    SemanticDocumentSearchTool,
)
from .evidence_selection import (
    ConceptRoleSelector,
    ParagraphDirectSelector,
    SelectionRequest,
    SelectionResult,
    adapt_legacy_selector,
)
from .ports import (
    AgentTool,
    AnswerSynthesizer,
    DocumentSearchTool,
    EvidenceSelector,
    WebSearchTool,
    require_agent_tool,
)
from .policies import (
    BudgetDecision,
    BudgetPolicy,
    BudgetTimeoutError,
    call_with_budget,
    check_budget,
    enforce_budget,
    execute_with_budget,
    run_with_budget,
)

__all__ = [
    "AgentOutcome",
    "AgentQuestion",
    "BudgetCall",
    "BudgetExhaustedError",
    "BudgetSnapshot",
    "Citation",
    "ClarificationRequest",
    "EvidenceItem",
    "EvidenceLedger",
    "EvidenceSourceType",
    "RunBudget",
    "SearchTrace",
    "SelectionStrategy",
    "DocumentSearchResult",
    "DocumentSearchService",
    "DocumentSearchStatus",
    "DocumentSearchToolAdapter",
    "SemanticDocumentSearchTool",
    "SelectionRequest",
    "SelectionResult",
    "ParagraphDirectSelector",
    "ConceptRoleSelector",
    "adapt_legacy_selector",
    "AgentTool",
    "AnswerSynthesizer",
    "DocumentSearchTool",
    "EvidenceSelector",
    "WebSearchTool",
    "require_agent_tool",
    "BudgetDecision",
    "BudgetPolicy",
    "BudgetTimeoutError",
    "call_with_budget",
    "check_budget",
    "enforce_budget",
    "execute_with_budget",
    "run_with_budget",
]
